{% set name = "pennylane-lightning" %}
{% set version = "0.20.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 710cf0400f1ee31692009645aa52b386860270ff6499e33a2e13ef37fcc93447
  patches:
    - 0001-Non-ninja.patch

build:
  number: 0
  # https://github.com/PennyLaneAI/pennylane-lightning/issues/192
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - make
  host:
    - libblas
    - liblapacke
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
  run:
    - ninja
    - numpy
    - pennylane >=0.15
    - python

test:
  imports:
    - pennylane_lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PennyLaneAI/pennylane-lightning
  summary: PennyLane-Lightning plugin
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane-lightning.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
