{% set name = "pennylane-lightning" %}
{% set version = "0.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c6a510ec576d4fd09751c0492100964b9598780f30370a1e36b7577adbd1e551
  patches:
    - 0001-Non-ninja.patch
    # Ninja is not recognised by pip check.

build:
  number: 0
  skip: true  # [win and vc<14]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    # Needed for Windows
    - cmake
    - ninja
    - make
  host:
    - libblas
    - liblapacke
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
  run:
    - ninja
    - numpy
    - pennylane >=0.19
    - python

test:
  imports:
    - pennylane_lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PennyLaneAI/pennylane-lightning
  summary: PennyLane-Lightning plugin
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane-lightning.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
