{% set name = "pennylane-lightning" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 34fe32d6c18b3088e1d23d4b5fd583b194749914beb2cdf2603d19aa7a89ef4a
  patches:
    - 0001-Remove-Werror.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapacke
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
  run:
    - numpy
    - pennylane >=0.15
    - python

test:
  imports:
    - pennylane_lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PennyLaneAI/pennylane-lightning
  summary: PennyLane-Lightning plugin
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane-lightning.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
